version: "3.8"
services:
  NOTRUST-WebHello:
    image: gsr38/nto-hellowebapp
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 2
    volumes:
     - nfs-www:/var/www/nto
    networks:
     - default
     - backend
 
networks:
  default:
    name: NotrustNetwork_Overlay_1300
    external: true
  backend:
    name: Backend-Network
  
volumes:
  nfs-www:
    external: true
